version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "postgresql-pass"
    restart: always
    volumes:
      - pgdatavol:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/ssgl
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdatavol:
